### ISSUE TITLE
redmine migration error plugin

### ISSUE THREAD

**Issue by undigo** [Ultragreen/redmine-appmenuadds#1]
Hi,

When I try to install your plugin rake task go down ... a solution ?

RAILS_ENV=production rake redmine:plugins:migrate --trace
rake aborted!
uninitialized constant Menutab
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/plugins/redmine-appmenuadds/init.rb:16:in `block in <top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/redmine/plugin.rb:73:in`instance_eval'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/redmine/plugin.rb:73:in `register'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/plugins/redmine-appmenuadds/init.rb:5:in`<top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/redmine/plugin.rb:130:in `block in load'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/redmine/plugin.rb:121:in`each'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/redmine/plugin.rb:121:in `load'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/config/initializers/30-redmine.rb:12:in`<top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/engine.rb:587:in`each'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/engine.rb:587:in `block in <class:Engine>'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/initializable.rb:30:in`instance_exec'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/initializable.rb:30:in `run'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/initializable.rb:55:in`block in run_initializers'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/initializable.rb:54:in `each'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/initializable.rb:54:in`run_initializers'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/application.rb:136:in `initialize!'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in`method_missing'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:32:in`require'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/plugins/redmine_dmsf/lib/tasks/dmsf_convert_documents.rake:32:in `<top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/tasks/redmine.rake:126:in`load'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/tasks/redmine.rake:126:in `block in <top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/tasks/redmine.rake:126:in`each'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/lib/tasks/redmine.rake:126:in `<top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/engine.rb:425:in`load'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/engine.rb:425:in `block in load_tasks'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/engine.rb:425:in`each'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/engine.rb:425:in `load_tasks'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/application.rb:145:in`load_tasks'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/home/adminzm/rubystack-1.9.3-14_V2/apps/redmine/htdocs/Rakefile:7:in`<top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in`load_rakefile'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/application.rb:82:in`block in load_rakefile'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/application.rb:81:in`load_rakefile'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `block in run'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/gems/rake-0.9.2.2/bin/rake:33:in`<top (required)>'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/bin/rake:19:in `load'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/bin/rake:19:in`<main>'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `eval'
/home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in`<main>'

gem env
RubyGems Environment:
- RUBYGEMS VERSION: 1.8.25
- RUBY VERSION: 1.9.3 (2013-06-27 patchlevel 448) [x86_64-linux]
- INSTALLATION DIRECTORY: /home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448
- RUBY EXECUTABLE: /home/adminzm/rubystack-1.9.3-14_V2/rvm/rubies/ruby-1.9.3-p448/bin/ruby
- EXECUTABLE DIRECTORY: /home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86_64-linux
- GEM PATHS:
  - /home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448
  - /home/adminzm/rubystack-1.9.3-14_V2/rvm/gems/ruby-1.9.3-p448@global
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

**Comment by devaroop** [comment]
Please download the latest build from https://github.com/devaroop/redmine-appmenuadds and follow README guidelines. It is now fixed. Let us know if any problems.

**Comment by lecid** [comment]
it´s now merged on this repository too
