### ISSUE TITLE
"Add tab for a internal project wiki page" doesn't add a new menu

### ISSUE THREAD

**Issue by abunimeh** [Ultragreen/redmine-appmenuadds#4]
(1) Add tab for URL page (2) Add tab for a custom wiki page, work without any issues. However, I cannot get "Add tab for a internal project wiki page" to display a menu

Environment:
Redmine version 2.5.2.stable.13231
Ruby version 1.9.3-p194 (2012-04-20) [x86_64-linux]
Rails version 3.2.19
Environment production
Database adapter Mysql2
SCM:
Subversion 1.6.17
Mercurial 2.2.2
Bazaar 2.6.0
Git 1.7.10.4
Filesystem

Redmine plugins:
appmenuadds 1.4.2
extended_fields 0.2.3
redmine_scm 0.5.0b

**Comment by lecid** [comment]
should be fixed by the last release
