### ISSUE TITLE
Can't open menu page

### ISSUE THREAD

**Issue by astebert** [Ultragreen/redmine-appmenuadds#5]
in production.log : 
Started GET "/menutabs/index" for 172.16.11.159 at 2014-07-28 17:14:14 +0200

ActionController::RoutingError (uninitialized constant MenutabsController):
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:230:in `block in constantize'
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:229:in`each'
  activesupport (3.2.19) lib/active_support/inflector/methods.rb:229:in `constantize'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:69:in`controller_reference'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:54:in `controller'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:32:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.19) lib/action_dispatch/routing/route_set.rb:608:in`call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.19) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.19) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in`_run__3818293386814276168__call__1742945911981851093__callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.19) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.19) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.19) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.19) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.19) lib/active_support/tagged_logging.rb:22:in`tagged'
  railties (3.2.19) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.19) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.19) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.19) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.19) lib/rails/engine.rb:484:in `call'
  railties (3.2.19) lib/rails/application.rb:231:in`call'
  railties (3.2.19) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.46) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in`process_request'
  passenger (4.0.46) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.46) lib/phusion_passenger/request_handler/thread_handler.rb:109:in`main_loop'
  passenger (4.0.46) lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

server configuration : 
Environment:
  Redmine version                2.5.2.stable.13333
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.10.4
  Filesystem  
Redmine plugins:
  appmenuadds                    1.4.2
  redmine_create_git             0.1.0
  redmine_documents              1.0.0
  redmine_ics_export             3.0.0.dev
  redmine_image_clipboard_paste  1.0.0
  redmine_issue_checklist        2.0.5
  redmine_landing_page           1.0.0
  redmine_logs                   0.0.5
  sidebar                        0.1.2
  timecop                        0.0.1

**Comment by lecid** [comment]
cant reproduce verify setup like in the readme

**Comment by ghost** [comment]
I had exactly same exception here...
Problem was fixed when I changed plugin folder name from redmine-appmenuadds to appmenuadds...
Now I see in install instructions it is made with git clone with additional parameter...
Strange when plugin folder should have different name than plugin repository...
